# Generated by Django 5.1.2 on 2024-10-21 21:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
